### ISSUE TITLE
Version in Python

### ISSUE THREAD

**Issue by marquezj** [IAEA-NDS/endf-parserpy#5]
Hi Georg. Congratulations on the new release. 

I think it would be useful to make the version of the package available in Python, for instance as `endf_parserpy.__version__`.

(If it is available somewhere else in the code, I could not find it)

Best,
    Ignacio

**Comment by marquezj** [comment]
One more comment: the package metadata shows version 0.0.0, likely from [here](https://github.com/IAEA-NDS/endf-parserpy/blob/461c83349d57c6e23101ec98b84a80d179b315ca/pyproject.toml#L3).

**Comment by gschnabel** [comment]
Hi Ignacio,
Thanks for your nice words regarding the new release. 

I think it is a good idea to put the version number into the code so that it is accessible via ```endf_parserpy.__version__``` for convenience and I will do that. One option that is already available now for retrieving the version number (requiring Python 3.8 or higher) is using the ```importlib``` package functionality:
```
import importlib.metadata
importlib.metadata.version("endf_parserpy")
```

The version number in the ```pyproject.toml``` file is intentionally kept at 0.0.0 and is dynamically updated based on the current git tag during the release and PyPI publishing workflow defined [here ](https://github.com/IAEA-NDS/endf-parserpy/blob/main/.github/workflows/publish_package.yml#L78).

**Comment by gschnabel** [comment]
The version number is now stored in the `__version__` variable in `endf_parserpy/__init__.py` and therefore accessible via `endf_parserpy.__version__`. The version number in the `pyproject.toml` file is automatically updated using the `__version__` variable during the build process launched via `pip install` or similar. In this way, an appropriate version string is accessible irrespective of whether the package has been cloned or installed via a package manager. The commit implementing these changes is 37b094e.
